"""Canonical column names and column validation helpers."""

from __future__ import annotations

import unicodedata
from enum import StrEnum

import pandas as pd


class HeatColumn(StrEnum):
    """Canonical columns expected in the heat_stress_report input."""

    TIMESTAMP = "timestamp"
    DEVICE = "dispositivo"
    TEMPERATURE = "temperature"
    HUMIDITY = "humidity"


class MonitoramentoColumn(StrEnum):
    """Canonical monitoring columns used by the correction pipeline."""

    DATETIME = "data_hora"
    ANIMAL_ID = "brinco"

    TEMPERATURE_COMPOST_1 = "temperatura_compost_1"
    HUMIDITY_COMPOST_1 = "humidade_compost_1"
    THI_COMPOST_1 = "thi_compost1"

    TEMPERATURE_COMPOST_2 = "temperatura_compost_2"
    HUMIDITY_COMPOST_2 = "humidade_compost_2"
    THI_COMPOST_2 = "thi_compost2"


class AuditColumn(StrEnum):
    """Canonical audit/report columns generated by the correction pipeline."""

    COMPOST = "compost"
    DEVICE = "dispositivo"
    LAG_HOURS = "lag_hours"
    OVERLAP_HOURS = "overlap_hours"
    CORR_TEMP = "corr_temp"
    CORR_HUMIDITY = "corr_humidity"
    MAE_TEMP = "mae_temp"
    MAE_HUMIDITY = "mae_humidity"
    SCORE = "score"


HEAT_REQUIRED_COLUMNS: list[str] = [
    HeatColumn.TIMESTAMP,
    HeatColumn.DEVICE,
    HeatColumn.TEMPERATURE,
    HeatColumn.HUMIDITY,
]

ENVIRONMENT_COLUMNS: list[str] = [
    MonitoramentoColumn.TEMPERATURE_COMPOST_1,
    MonitoramentoColumn.HUMIDITY_COMPOST_1,
    MonitoramentoColumn.THI_COMPOST_1,
    MonitoramentoColumn.TEMPERATURE_COMPOST_2,
    MonitoramentoColumn.HUMIDITY_COMPOST_2,
    MonitoramentoColumn.THI_COMPOST_2,
]

MONITORAMENTO_REQUIRED_COLUMNS: list[str] = [
    MonitoramentoColumn.DATETIME,
    *ENVIRONMENT_COLUMNS,
]

# Output contract consumed by merge_monitoramento_saude and carga-termica-bovinos.
CORRECTED_MONITORAMENTO_REQUIRED_COLUMNS: tuple[str, ...] = (
    MonitoramentoColumn.DATETIME,
    MonitoramentoColumn.TEMPERATURE_COMPOST_1,
    MonitoramentoColumn.HUMIDITY_COMPOST_1,
    MonitoramentoColumn.THI_COMPOST_1,
    MonitoramentoColumn.TEMPERATURE_COMPOST_2,
    MonitoramentoColumn.HUMIDITY_COMPOST_2,
    MonitoramentoColumn.THI_COMPOST_2,
)

# Accepted spelling aliases. The historical dataset uses "humidade".
COLUMN_ALIASES: dict[str, str] = {
    "umidade_compost_1": MonitoramentoColumn.HUMIDITY_COMPOST_1,
    "umidade_compost_2": MonitoramentoColumn.HUMIDITY_COMPOST_2,
    "humidity_compost_1": MonitoramentoColumn.HUMIDITY_COMPOST_1,
    "humidity_compost_2": MonitoramentoColumn.HUMIDITY_COMPOST_2,
}


def normalize_col(name: str) -> str:
    """Normalize a column name to a simple ASCII snake-like form."""

    s = unicodedata.normalize("NFKD", str(name)).encode("ascii", "ignore").decode("ascii")
    return (
        s.strip()
        .lower()
        .replace(" ", "_")
        .replace(".", "")
        .replace("/", "_")
        .replace("-", "_")
    )


def canonicalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Return a DataFrame with known aliases renamed to canonical names."""
    renamed = {
        column: COLUMN_ALIASES.get(normalize_col(column), normalize_col(column))
        for column in df.columns
    }
    return df.rename(columns=renamed)


def require_columns(df: pd.DataFrame, required: list[str] | tuple[str, ...], df_name: str) -> None:
    """Validate that required columns are present in a DataFrame."""

    missing = [str(c) for c in required if str(c) not in df.columns]
    if missing:
        raise ValueError(f"Colunas obrigatórias ausentes em {df_name}: {missing}")
